### ISSUE TITLE
Kanban board does not seem to work with MySql

### ISSUE THREAD

**Issue by SamiInnovate** [ConorWebb96/bb-kanban-draggable#4]
First of all, great plugin – it's super useful! 

I'm having issues getting the Kanban board to work with MySQL tables. The demo app works as expected, but when I try to set up the plugin with MySQL, it doesn't work.

**Comment by ConorWebb96** [comment]
Hey @SamiInnovate,

Spent a bit of time earlier looking into this. Originally it wasn't made to account for datasource plus. Somehow, it works with it anyway, I've supplied the below sql schema I used which works with this plugin.

```
CREATE TABLE State (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Title TEXT,
    `Order` FLOAT
);

CREATE TABLE Tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fk_states_tickets INT,
    Title TEXT,
    Description TEXT,
    CONSTRAINT tickets2_fk_states_tickets_foreign FOREIGN KEY (fk_states_tickets) REFERENCES states(id)
);
```

Table names don't matter and the configuration is the exact same, I will say that this won't support images showing within the cards, I may extend the plugin at some point so it can use urls for images. 

I hope this helps!
