### ISSUE TITLE
handling of multiple boards

### ISSUE THREAD

**Issue by stereo9** [ConorWebb96/bb-kanban-draggable#6]
it would be quite nice to have the option to use different kanban boards on the same page, e.g. to allow multi user access or management of multiple projects at the same time.

the easiest way i can imagine this would be to add an ID to each board which filters for a "project id" in the database

thoughts?

**Comment by ConorWebb96** [comment]
It will likely be resolved whenever changes involve this user's [request](https://github.com/ConorWebb96/bb-kanban-draggable/issues/7). Should simplify the setup. You can do it currently, but you just have to ensure everything is setup correctly.
